### DISCUSSION TITLE
Double-Take and difference from forked source

### DISCUSSION THREAD

**Discussion by Dvalin21** [skrashevich/double-take#126] [Q&A] [answered]
Hello and thank you so much for picking up the torch.

I Wanted to ask a few question.

1. I noticed that image size is small than what was forked from jakowenko by at least half. What are the major differences?
2. Are there any plans to support other NVRs like OSNVR or Viseron?
3. I noticed in the configuration there is a setup for Frigate or the Cameras directly. I wanted to know is there a difference in performance between and if so which is better?
4. What is a generic best practice when using Double-Take? 
  Here is my cofg for Deepstack in DT config. I'm not using CompreFace because I don't have a Nvidia GPU
  You will notice that the numbers are on the higher side as I'm starting out higher and slowly reducing the to
  see which would give the positives and the fewest false positives and false negatives.

     recognize:
       min_face_size: 500 # minimum face size to be recognized (pixels)
       recognition_threshold: 0.79 # threshold for face recognition confidence
       det_prob_threshold: .87
       match_timeout: 20 # time (in seconds) to wait before recognizing the same person again
       reidentification_interval: 0 # time (in seconds) to wait before re-identifying a person
       face_template_scale: 1.0 # scale factor for the face template (values between 0.25 and 1.0)
       templates_cache_size: 2000 # maximum number of face templates to keep in cache
 5. And lastly what is the best image height to pass through to Codeprject.AI?

Anyway, thank you so much again for your work. Keep up the good work your doing. I can't contribute as far as work, but know Ill be passing along a few cups of coffee. Thanks.

PS: Ill go ahead give you a run down of my setup.
Frigate NVR on Lxc
OS: Proxmox VE 8.0.4 x86_64 
Host: B550 AORUS ELITE AX 
Kernel: 6.2.16-14-pve 
Uptime: 1 hour, 43 mins 
Packages: 824 (dpkg) 
Shell: bash 5.2.15 
Resolution: 1920x1080 
Terminal: /dev/pts/0 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: AMD ATI Radeon RX 5500/5500M / Pro 5500M 
Memory: 4417MiB / 64194MiB

**Comment by skrashevich** [comment, marked as answer]
1. The image size is optimized by improving the image build process in Dockerfile
2. At the moment, there are no such plans. But any other NVRs can use double-take using the [API(https://github.com/skrashevich/double-take?tab=readme-ov-file#api)
3. no performance difference. manual cameras configuration can be used for integrate with other NVRs
5. 640x640px. ai.server use YOLOv5 model for face recognition, which supports only this resolution for input image

**Reply by Dvalin21** [reply]
Thanks for the answers. I really appreciate it. Ill look forward to ai.server work out the bugs for Google Coral M.2 use.

**Reply by krzakx** [reply]
Hey can you give more details about your install as you said:

Frigate NVR on Lxc

Is that really Frigate on LXC system container or this system container does include additional Docker container.

I am also looking forward utilize Google Coral Tensor Flow technology so would be really appreciated for any your updates on your investigation.

**Reply by Dvalin21** [reply]
So I can take you through what I use. 
So to make things super easy, I use the scripts from https://tteck.github.io/Proxmox/

I use his docker lxc (Which is a lxc of Ubuntu or Debian, it ask which one you want to use). When its finished installing, it will ask if you want to go ahead and install portainer and docker-compose. From there you just set up your folders as needed and install as needed. Here is a copy of my docer-compose
```
version: "3.9"
services:
  frigate:
    container_name: Frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2g" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config/config.yml:/config/config.yml:rw
      - /home/frigate/config/:/config/
      - /home/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 12GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 12000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1935:1935"
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
      - PLUS_API_KEY=

  mqtt:
    container_name: Frigate-Mqtt
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/frigate/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/frigate/mosquitto/log:/mosquitto/log
      - /home/frigate/mosquitto/data:/mosquitto/data
    restart: unless-stopped

  codeproject:
    container_name: Frigate-AI
    image: codeproject/ai-server #If you have a Nvidia GPU, you can change this to codeproject/ai-server:gpu
    devices:
      - /dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    ports:
      - "32168:32168"
    volumes:
      - /home/frigate/codeproject/ai:/etc/codeprject/ai
      - /home/frigate/codeproject/ai:/app/modules
    restart: unless-stopped

  double-take:
    container_name: Frigate-Doubletake
    image: skrashevich/double-take:latest

    ports:
      - "3000:3000"
    volumes:
      - /home/frigate/double-take:/.storage
    restart: unless-stopped
```
Let me know if this helps. If you have more issues come to the discord channel and myself and others can further assist. https://discord.gg/YAbQM6tJ
