### DISCUSSION TITLE
Messages send to Gotify give a error in Double Take

### DISCUSSION THREAD

**Discussion by francoisduprez** [skrashevich/double-take#135] [Q&A]
I had a working system with Frigate, HA, Double Take and Gotify but after playing with the system it stoped working and i don't know what went wrong.

**This is the error:**

```
"23-10-09 15:00:14 verbose: Incoming event from frigate: {"before": {"id": "1696856393.50396-5xwi1g", "camera": "Voordeur", "frame_time": 1696856408.721869, "snapshot": {"frame_time": 1696856407.573293, "box": [146, 70, 408, 473], "area": 105586, "region": [45, 4, 521, 480], "score": 0.76953125, "attributes": []}, "label": "person", "sub_label": null, "top_score": 0.84375, "false_positive": false, "start_time": 1696856393.50396, "end_time": null, "score": 0.75390625, "box": [1, 181, 316, 478], "area": 93555, "ratio": 1.0606060606060606, "region": [0, 160, 320, 480], "stationary": false, "motionless_count": 1, "position_changes": 2, "current_zones": [], "entered_zones": ["Voordeur_Stoep"], "has_clip": true, "has_snapshot": true, "attributes": {}, "current_attributes": []}, "after": {"id": "1696856393.50396-5xwi1g", "camera": "Voordeur", "frame_time": 1696856409.242925, "snapshot": {"frame_time": 1696856407.573293, "box": [146, 70, 408, 473], "area": 105586, "region": [45, 4, 521, 480], "score": 0.76953125, "attributes": []}, "label": "person", "sub_label": null, "top_score": 0.84375, "false_positive": false, "start_time": 1696856393.50396, "end_time": 1696856414.327029, "score": 0.55859375, "box": [0, 246, 177, 476], "area": 40710, "ratio": 0.7695652173913043, "region": [0, 160, 320, 480], "stationary": false, "motionless_count": 3, "position_changes": 2, "current_zones": [], "entered_zones": ["Voordeur_Stoep"], "has_clip": true, "has_snapshot": true, "attributes": {}, "current_attributes": []}, "type": "end"}
23-10-09 15:00:14 info: processing voordeur: 3404afd6-a593-430e-9b0d-8ba1ace0d98d
23-10-09 15:00:14 info: done processing voordeur: 3404afd6-a593-430e-9b0d-8ba1ace0d98d in 0.14 sec
23-10-09 15:00:14 info: {
  id: '3404afd6-a593-430e-9b0d-8ba1ace0d98d',
  duration: 0.14,
  timestamp: '2023-10-09T13:00:14.667Z',
  attempts: 1,
  camera: 'voordeur',
  zones: [],
  counts: { person: 1, match: 0, miss: 1, unknown: 0 },
  matches: [],
  misses: [
    {
      name: 'francois',
      confidence: 98.48,
      match: false,
      box: [Object],
      checks: [Array],
      type: 'mqtt',
      duration: 0.11,
      detector: 'compreface',
      filename: '8f33721d-1fb1-48ed-b7a6-781e3ef4b6b5.jpg'
    }
  ],
  unknowns: []
}
23-10-09 15:00:14 error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/double-take/api/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:174:12)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at ServerResponse.json (/double-take/api/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:162:21)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at /double-take/api/src/app.js:46:38
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)"
```

**This is my Double Take config:**

```
mqtt:
  host: 192.168.1.44
  username: francois
  password: !secret mqtt_password

logs:
  level: debug

home_assistant:
      url: http://192.168.1.44:8123

frigate:
  url: http://192.168.1.44:5000

notify:
  gotify:
    url: https://gotify.mirmooi.net/
    token: !secret gotify_token

detectors:
  compreface:
    url: http://192.168.1.44:8000
    key: !secret compreface_key
```

**This is the docker-compose.yaml fot Double Take:**

```
version: '3.7'

networks:
  frigate:
    name: frigate
    driver: bridge
    external: true

services:
  double-take:
    container_name: double-take
    image: skrashevich/double-take:latest
#    image: jakowenko/double-take:latest
    restart: unless-stopped
    volumes:
      - /home/docker/docker_data/double-take:/.storage
    ports:
      - 3000:3000
    environment:
      PUID: "1002"
      PGID: "985"
      TZ: "Europe/Amsterdam"
    networks:
      - "frigate"
```

Gotify is behind a reverse proxy (Nginx Proxy Manager) and is accessible through my phone outside my network.
