### DISCUSSION TITLE
Removing attributes from Home Assistant recorder

### DISCUSSION THREAD

**Discussion by pdobrien3** [skrashevich/double-take#170] [General]
I am getting a bunch of these warnings in the Home Assistant logs:

`State attributes for sensor.double_take_person_1 exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored`

I realize I can do this:

```
logger:
  default: info
  logs:
    homeassistant.components.recorder.db_schema: error
```

and this:

```
recorder:
  exclude:
    entities:
      - sensor.double_take_person_1
```
but neither seems optimal.  I do have `base64: false` in my double take config but this doesn't seem to solve the problem.  I would like to see the state of my double tale sensors.  Is there an elegant way to handle this?
