### DISCUSSION TITLE
Attribute 'count' of the double take created sensor

### DISCUSSION THREAD

**Discussion by backslashV** [skrashevich/double-take#362] [Q&A]
I'm not sure I fully understand the count attribute for one of the sensors double take creates.
```
counts:
  person: 0
  match: 1
  miss: 0
  unknown: -1
```
1) is _unknown_ supposed to be people double take hasn't recognized? why is it a negative # sometimes?
2) is _miss_ people that double take has recognized but can't report as a match because either the area is too small or the confidence too low?
3) does _person_ equal _miss + match + unknown_?
