### DISCUSSION TITLE
low resolution snapshots

### DISCUSSION THREAD

**Discussion by elektrinis** [skrashevich/double-take#533] [Q&A]
I think I need some help configuring this. I have a 4K overhead camera and typical face size should be around 150x150 px.
However, I am getting snapshots that are not cropped (full camera view), but resized to 500px height, after which face size becomes 30x30 px or so, and accurate detection becomes impossible. I don't know where this resizing is coming from and why it's not cropped to person, so please help me figuring this out. My config is below.
````
# Double Take
mqtt:
  host: core-mosquitto
  username: ****
  password: ****
  crop: True
  quality: 100
#  height: 500
  timestamp: false
  attempts:
    latest: 0
    snapshot: 0

frigate:
  url: http://192.168.88.10:5000
  cameras:
   - cam1
  attempts:
    latest: 2
    # number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 2
    # process frigate images from frigate/+/person/snapshot topics
    mqtt: false
    # add a delay expressed in seconds between each detection loop
    delay: 0
  min_area: 8000
  labels:
   - person
  update_sub_labels: true
#  image:
    # height of frigate image passed for facial recognition
#    height: 500
  crop: true
  
detectors:
#  deepstack:
#    url: http://192.168.88.4:5002
#    key: ""
  compreface:
    url: http://192.168.88.4:8000
    key: "******"
    det_prob_threshold: 0.7

detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 85
    # hours to keep match images until they are deleted
    purge: 168
    # minimum area in pixels to consider a result a match
    min_area: 8000
    
  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a name as unknown
    confidence: 40
    # hours to keep unknown images until they are deleted
    purge: 8
    # minimum area in pixels to keep an unknown result
    min_area: 0
```
