### DISCUSSION TITLE
Amazon Rekognition

### DISCUSSION THREAD

**Discussion by ryryridd99** [skrashevich/double-take#596] [Q&A]
Can anyone give me some pointers on what is required to get the Amazon rekognition software working in double-take for facial rekognition?

**Comment by vdiogo** [comment]
Check this video on how to setup aws account https://youtu.be/1G8tnhw2N_Y

Then, you update double-take config with the following:

```
  rekognition:
    aws_access_key_id: !secret aws_access_key
    aws_secret_access_key: !secret aws_secret_access_key
    aws_region: eu-west-1 #this is in Ireland, default is us-east-1
    collection_id: double-take
    # require opencv to find a face before processing with detector
    opencv_face_required: true
```
