### DISCUSSION TITLE
double-take without frigate

### DISCUSSION THREAD

**Discussion by semikor** [skrashevich/double-take#607] [Q&A] [answered]
Hello everyone!
Tell me, please! How can I use double-take without frigate?
What values and which topics should be sent via mqtt to receive a photo and recognize it?
I tried to send from node-red to the frigate/camera2/person/snapshot topic as a buffer, but nothing happens. If add photo manually through the double-take interface, the recognition works.

**Comment by semikor** [comment]
How do I transfer a photo from node-red to double-take for face recognition?
I am sending the photo itself to the topic frigate/camera2/person/snapshot - double-take doesn't react in any way ((
Need to send something else to the topic frigate/events ? But what exactly???
Please help me figure this out!

**Comment by townsmcp** [comment, marked as answer]
@semikor the following Node Red code might help you:
```
[{"id":"ca8b1b4f6dd1d0fc","type":"tab","label":"Flow 2","disabled":false,"info":"","env":[]},{"id":"14b78559b30b8a70","type":"http request","z":"ca8b1b4f6dd1d0fc","name":"Send to Double Take","method":"GET","ret":"bin","paytoqs":"ignore","url":"http://192.168.1.198:3000/api/recognize?url=http://192.168.1.173/snap.jpeg&attempts=15&break=true&camera=door","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":540,"y":120,"wires":[["ce8da7ae6627cb6f","7ca7dfd274504efe"]]},{"id":"2c7bed40f1fd51ef","type":"inject","z":"ca8b1b4f6dd1d0fc","name":"Doorbell","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"test","payloadType":"str","x":320,"y":120,"wires":[["14b78559b30b8a70"]]},{"id":"ce8da7ae6627cb6f","type":"image","z":"ca8b1b4f6dd1d0fc","name":"Doorbell Preview","width":"200","data":"payload","dataType":"msg","thumbnail":false,"active":false,"pass":false,"outputs":0,"x":750,"y":160,"wires":[]},{"id":"7ca7dfd274504efe","type":"debug","z":"ca8b1b4f6dd1d0fc","name":"debug 46","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":720,"y":100,"wires":[]},{"id":"c782913111a43f82","type":"server-state-changed","z":"ca8b1b4f6dd1d0fc","name":"Doorbell Smart Motion","server":"60e3c8e2.b47df8","version":5,"outputs":2,"exposeAsEntityConfig":"","entityId":"binary_sensor.doorbell_person_detected","entityIdType":"exact","outputInitially":false,"stateType":"str","ifState":"on","ifStateType":"str","ifStateOperator":"is","outputOnlyOnStateChange":true,"for":"0","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":260,"y":160,"wires":[["14b78559b30b8a70"],[]]},{"id":"60e3c8e2.b47df8","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]
```
I have Unifi Protect cameras. When my doorbell sensor changes to true for person detection, the flow runs. The flow grabs a snapshot image from the Unifi camera and then parses that to Double Take API. 
`Send to Double Take` node can be broken down to:
http://192.168.1.198:3000/api/recognize?url=http://192.168.1.173/snap.jpeg&attempts=15&break=true&camera=door
where:
- `http://192.168.1.198:3000/api/recognize` is the DT API
- 'http://192.168.1.173/snap.jpeg' is the camera to grab a snapshot
- remaining options are DT variables to control the runs, break on match and give the camera a unique name to display on DT processing.

The image node uses plugin `node-red-contrib-image-output`

**Reply by semikor** [reply]
> API Double Take
[This API ?](https://documenter.getpostman.com/view/1013188/TzsWuAa8#d19e99ab-adff-4ce6-9647-5e3db7e4d452)

Thank YOU very much!
It seems to have worked out))
I have a problem, NVR takes pictures of faces and sends the address of the link to the picture, but to get the picture itself, you need to enter the login:password of the registrar.

**Reply by townsmcp** [reply]
What NVR are you using? If you are using Unifi, by default you need to enter a username and password however it can be configured so no username/password is needed but it is not set that way out of the box

**Reply by semikor** [reply]
> What NVR are you using? If you are using Unifi, by default you need to enter a username and password however it can be configured so no username/password is needed but it is not set that way out of the box

Hikvision

**Reply by townsmcp** [reply]
Sorry, I have no ideas. Havent used that make before. However, it might be like Unifi in that by default the snapshot endpoint is locked down to a username/password that you can configure to allow directly grabbing the snapshot. To enable that functionality on Unifi you have to browse to the camera directly and change its settings on the camera rather than on the NVR.

A quick Google seems to point to snapshot endpoint access via `http://admin:xxxx@192.168.0.xx/ISAPI/Streaming/channels/101/picture`
(see https://ipcamtalk.com/threads/get-still-image-through-url-from-hikvision-nvr-solved.6279/)

**Reply by semikor** [reply]
> Быстрый поиск в Google, похоже, указывает на доступ к конечной точке моментального снимка через `http://admin:xxxx@192.168.0.xx/ISAPI/Streaming/channels/101/picture`

Yes, that's exactly how I set it up now.
But it works somehow unstable (( Sometimes it returns errors.

**Reply by semikor** [reply]
> * remaining options are DT variables to control the runs, break on match and give the camera a unique name to display on DT processing.

How do you get the recognition result?
I listened to the topic homeassistant/sensor/double-take/# and filtered by name.
BUT after I disabled Frigate in the Double-Take config, the topic stopped updating (although recognition works).
How can I get the recognition result from Double-Take to Node-Red when Frigate is disabled?

**Comment by semikor** [comment]
How do you get the recognition result?
I listened to the topic homeassistant/sensor/double-take/# and filtered by name.
BUT after I disabled Frigate in the Double-Take config, the topic stopped updating (although recognition works).
How can I get the recognition result from Double-Take to Node-Red when Frigate is disabled?

**Reply by townsmcp** [reply]
The result goes straight into DT dashboard on person detection and recognition by Compreface. It also turns on the double take mqtt sensor for 10 minutes for the appropriate recognised person. By sending your image straight to the DT API (which goes into Compreface and back), you don’t need Frigate. DT config page does show a yellow icon for Frigate but it still works as long as you have mqtt configured in DT settings - HA sensor means you don’t need to use NR.
This is my config (lots of commented out options from various trials over time which can be ignored):
```
ui:
  pagination:
    # number of results per page
    limit: 28

  thumbnails:
    # value between 0-100
    quality: 95
    # value in pixels
    width: 500

home_assistant:
  url: http://192.168.1.198:8123
  token: XXXXX
  
# time settings (default: shown below)
time:
  # defaults to iso 8601 format with support for token-based formatting
  # https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens
  format: ttt dd-mm-yy
  # time zone used in logs
  timezone: Europe/London
    
mqtt:
  host: 192.168.1.198 # mqtt host
  user: mqtt-user
  password: XXXXX
  
  topics:
    # mqtt topic for frigate message subscription
    frigate: frigate/events
    #  mqtt topic for home assistant discovery subscription
    homeassistant: homeassistant
    # mqtt topic where matches are published by name
    matches: double-take/matches
    # mqtt topic where matches are published by camera name
    cameras: double-take/cameras
    
# frigate:
#   url: http://192.168.1.233:5000
#   image:
#     height: 360
#   attempts:
#     latest: 15
#     snapshot: 0
# #   mqtt: false
#   update_sub_labels: false
#   # stop the processing loop if a match is found
#   # if set to false all image attempts will be processed before determining the best match
#   stop_on_match: true
#   # ignore detected areas so small that face recognition would be difficult
#   # quadrupling the min_area of the detector is a good start
#   # does not apply to MQTT events
#   min_area: 1200
#   # ignore detected areas so small that face recognition would be difficult
#   # quadrupling the min_area of the detector is a good start
#   # does not apply to MQTT events
#   # min_area: 1600
#   # object labels that are allowed for facial recognition
#   labels:
#     - person
#   zones:
#     - camera: doorbell
#       zone: garden_doorbell
#     # - camera: carport
#     #   zone: driveway_carport
#   cameras:        # NEWLY ADDED
#     - doorbell    # NEWLY ADDED
#     # - carport    # NEWLY ADDED

#   # override frigate attempts and image per camera
#   events:
#     doorbell:
#       attempts:         # NEWLY ADDED
#         latest: 15       # NEWLY ADDED
#         snapshot: 0     # NEWLY ADDED
#         mqtt: false     # NEWLY ADDED
#         # delay: 0        # NEWLY ADDED
#       image:
#         height: 1200
#         latest: http://192.168.1.173/snap.jpeg
#     # carport:
#     #   attempts:         # NEWLY ADDED
#     #     latest: 5       # NEWLY ADDED
#     #     snapshot: 0     # NEWLY ADDED
#     #     mqtt: false     # NEWLY ADDED
#     #     # delay: 0        # NEWLY ADDED
#     #   image:
#     #     height: 1512
#     #     latest: http://192.168.1.240/snap.jpeg
  
detectors:
  compreface:
    url: http://192.168.1.233:8000
    key: XXXXXX
    timeout: 15
    # minimum required confidence that a recognized face is actually a face value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    # face_plugins: gender,age
  # aiserver:
  #   url: http://192.168.1.233:32168
  #   # number of seconds before the request times out and is aborted
  #   timeout: 30
  #   # require opencv to find a face before processing with detector
  #   opencv_face_required: false
  #   # only process images from specific cameras, if omitted then all cameras will be processed
  #   # cameras:
  #   #   - front-door
  #   #   - garage
telemetry: false

detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 65
    # hours to keep match images until they are deleted
    purge: 48
    # minimum area in pixels to consider a result a match
    # min_area: 2500
    min_area: 1200
    # min_area: 21000
    # when using substream image, 3600
  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a name as unknown
    confidence: 30
    # hours to keep unknown images until they are deleted
    purge: 48
    # minimum area in pixels to keep an unknown result
    min_area: 64
```
Here is what my dashboard looks like:
![IMG_1859](https://github.com/user-attachments/assets/20b54caf-23a4-4940-acae-f498ce82bc86)

**Reply by semikor** [reply]
> DT config page does show a yellow icon for Frigate but it still works as long as you have mqtt configured in DT settings - HA sensor means you don’t need to use NR.

My main system is node-red. Home Assistant - used as an additional (as a UI for wife and children)) ).
My dt config is similar to yours and if I put # on the frigate block, the frigate label disappears completely and stops sending recognition data to the homeassistant/sensor/double-take/# topic. Although the recognition itself works in dt.
Config with working frigate and notifications on homeassistant/sensor/double-take/# works:
```
# Double Take
# Learn more at https://github.com/skrashevich/double-take/#configuration

# enable mqtt subscribing and publishing (default: shown below)
mqtt:
  host: 192.168.1.25
  port: 1883
  username: mqtt
  password: pass
  #client_id:
  
frigate:
  url: http://192.168.1.25:5000
  # if double take should send matches back to frigate as a sub label
  # NOTE: requires frigate 0.11.0+
  update_sub_labels: true

  # stop the processing loop if a match is found
  # if set to false all image attempts will be processed before determining the best match
  stop_on_match: true

  # ignore detected areas so small that face recognition would be difficult
  # quadrupling the min_area of the detector is a good start
  # does not apply to MQTT events
  min_area: 0

  # object labels that are allowed for facial recognition
  labels:
    - person
    
  attempts:
    # number of times double take will request a frigate latest.jpg for facial recognition
    latest: 0
    # number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 1
    # process frigate images from frigate/+/person/snapshot topics
    mqtt: true
    # add a delay expressed in seconds between each detection loop
    delay: 0

  image:
    # height of frigate image passed for facial recognition
    height: 1000

  # only process images from specific cameras
  cameras:
    - Door
    - Camera2

# detector settings (default: shown below)
detectors:
  compreface:
    url: http://192.168.1.25:8000
    # recognition api key
    key: *******************************
    # number of seconds before the request times out and is aborted
    timeout: 10
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: true
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    # face_plugins: mask,gender,age
    # only process images from specific cameras, if omitted then all cameras will be processed
    cameras:
      - Door
      - Camera2

# global detect settings (default: shown below)
detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 93
    # hours to keep match images until they are deleted
    purge: 720
    # minimum area in pixels to consider a result a match
    min_area: 10000

  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a name as unknown
    confidence: 85
    # hours to keep unknown images until they are deleted
    purge: 720
    # minimum area in pixels to keep an unknown result
    min_area: 5000

# time settings (default: shown below)
time:
  # defaults to iso 8601 format with support for token-based formatting
  # https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens
  format: "yyyy-LL-dd HH:mm:ss"
  # time zone used in logs
  timezone: Europe/Moscow

notify:
  telegram:
    token: **********************
    #KSM:
    chat_id: "1111111111"
```
![Снимок экрана 2024-10-16 090600](https://github.com/user-attachments/assets/046d3a9a-b6cf-4bec-8fa5-c20987024e9c)

and if so, then mqtt notifications stop coming to homeassistant/sensor/double-take/#

```
# Double Take
# Learn more at https://github.com/skrashevich/double-take/#configuration

# enable mqtt subscribing and publishing (default: shown below)
mqtt:
  host: 192.168.1.25
  port: 1883
  username: mqtt
  password: pass
  #client_id:
  
#frigate:
#  url: http://192.168.1.25:5000
  # if double take should send matches back to frigate as a sub label
  # NOTE: requires frigate 0.11.0+
#  update_sub_labels: true

  # stop the processing loop if a match is found
  # if set to false all image attempts will be processed before determining the best match
#  stop_on_match: true

  # ignore detected areas so small that face recognition would be difficult
  # quadrupling the min_area of the detector is a good start
  # does not apply to MQTT events
#  min_area: 0

  # object labels that are allowed for facial recognition
#  labels:
#    - person
    
#  attempts:
    # number of times double take will request a frigate latest.jpg for facial recognition
#    latest: 0
    # number of times double take will request a frigate snapshot.jpg for facial recognition
#    snapshot: 1
    # process frigate images from frigate/+/person/snapshot topics
#    mqtt: true
    # add a delay expressed in seconds between each detection loop
#    delay: 0

#  image:
    # height of frigate image passed for facial recognition
#    height: 1000

  # only process images from specific cameras
#  cameras:
#    - Door
#    - Camera2

# detector settings (default: shown below)
detectors:
  compreface:
    url: http://192.168.1.25:8000
    # recognition api key
    key: *******************************
    # number of seconds before the request times out and is aborted
    timeout: 10
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: true
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    # face_plugins: mask,gender,age
    # only process images from specific cameras, if omitted then all cameras will be processed
    cameras:
      - Door
      - Camera2

# global detect settings (default: shown below)
detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 93
    # hours to keep match images until they are deleted
    purge: 720
    # minimum area in pixels to consider a result a match
    min_area: 10000

  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a name as unknown
    confidence: 85
    # hours to keep unknown images until they are deleted
    purge: 720
    # minimum area in pixels to keep an unknown result
    min_area: 5000

# time settings (default: shown below)
time:
  # defaults to iso 8601 format with support for token-based formatting
  # https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens
  format: "yyyy-LL-dd HH:mm:ss"
  # time zone used in logs
  timezone: Europe/Moscow

notify:
  telegram:
    token: **************************************
    #KSM:
    chat_id: "111111111111111"
```
![Снимок экрана 2024-10-16 091319](https://github.com/user-attachments/assets/6314405f-d730-4642-ae11-f9f56d97662f)

**Reply by townsmcp** [reply]
You are missing the `topics` section from DT config. I would guess that your mqtt configure is coming in from frigate. By killing off frigate you have no entries going into mqtt. If you look at my config, near the beginning under the mqtt integration settings I have the following:
```
  topics:
    # mqtt topic for frigate message subscription
    frigate: frigate/events
    #  mqtt topic for home assistant discovery subscription
    homeassistant: homeassistant
    # mqtt topic where matches are published by name
    matches: double-take/matches
    # mqtt topic where matches are published by camera name
    cameras: double-take/cameras
```
Add this section back (you might want to tweak it to use the same topics as frigate for consistency?) you should then get it working fine as you are then explicitly stating the topics to publish to rather than using default/reading mqtt only.

I also notice you dont have the `home_assistant` section in your config - Im not sure if that would also be significant?
```
home_assistant:
  url: http://192.168.1.198:8123
  token: XXXX
```

Also, what version of DT do you have installed? I am running v1.13.11.9rc2
