### DISCUSSION TITLE
MQTT only with frigate 0.14.1

### DISCUSSION THREAD

**Discussion by hameno** [skrashevich/double-take#615] [Q&A]
I'm trying to setup mqtt only detection with frigate 0.14.1 - I'm using aiserver and the following config:

```
mqtt:
  host: core-mosquitto    

frigate:
  url: http://ccab4aaf-frigate:5000
  attempts:
    latest: 0
    snapshot: 0
    mqtt: true
    delay: 1
detectors:
  aiserver:
    url: http://0a217ee8-ai.server:5000
```

I see events processed but no images appear in matches nor does double-take detect anything. I  debugged mqtt and I can see that images are published in the topic. 

What am I missing?
