### ISSUE TITLE
[BUG] dt not recognizing me in trained image

### ISSUE THREAD

**Issue by nabheet** [skrashevich/double-take#178]
**Describe the bug**
Again, I am not sure this is a bug. More about how to use DT. I have trained it to recognize me in 3 different images.  Two of the images are a close up of my face and third is a bigger body shot. It is only recognizing me in the body shot image. I would like to understand how to configure the system so it can recognized me in different situations. Or if this is even possible.

If I remove the non-closeup image from the training set, it recognizes me.

**Version of Double Take**
`1.13.11.8`

**Expected behavior**
I would think it would recognize me in all the trained images.

**Screenshots**
![image](https://github.com/skrashevich/double-take/assets/1319809/5c1fedd5-cd8f-4d62-8926-64a08539a61b)
![image](https://github.com/skrashevich/double-take/assets/1319809/567dda4f-2332-4a2d-ac24-538824302654)

**Hardware**
 - Architecture or platform: AMD64
 - OS: Ubuntu
 - Browser: Chrome and Safari
 - Docker image: latest

**Additional context**
N/A

**Comment by skrashevich** [comment]
What recognition system do you use? Show the configuration files

**Comment by nabheet** [comment]
Both Codeproject.AI and Deepstack, all in one docker-compose.yaml.

```
---
auth: true

mqtt:
  host: m
  username: !secret mqtt_username
  password: !secret mqtt_password
  topics:
    frigate: frigate/+/person/snapshot

frigate:
  url: http://f:5000
  update_sub_labels: true
  labels:
    - face
  image:
    height: 640
  attempts:
    mqtt: true

detectors:
  deepstack:
    url: http://ds:5000
  aiserver:
    url: http://cpai:5000
```

Docker-compose.yaml:

```
  ds:
    image: deepquestai/deepstack:gpu
    environment:
      - VISION-FACE=True
      - VISION-OBJECT=True
    ports:
      - 7000:5000
    volumes:
      - deepstack_localstorage:/datastore
    healthcheck:
      test: ["CMD", "wget", "-q", "http://127.0.0.1:5000/", "-O -"]
      interval: 30s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: any
      placement:
          constraints:
            - node.labels.webproxy == true


  cpai:
    image: codeproject/ai-server:cuda12_2
    ports:
      - 32168:32168
    volumes:
      - codeproject_ai_data:/etc/codeproject/ai
      - codeproject_ai_modules:/app/modules
    healthcheck:
      test: ["CMD", "wget", "-q", "http://127.0.0.1:32168/", "-O -"]
      interval: 30s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: any
      placement:
          constraints:
            - node.labels.webproxy == true

  dt:
    image: skrashevich/double-take
    user: "1000"
    environment:
      - VIRTUAL_HOST=custom.domain.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=custom.domain.com
    volumes:
      - double_take_storage:/.storage/
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000'"]
      interval: 30s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.webproxy == true
```
