### ISSUE TITLE
[FEAT] Decrease time of recognised state - MQTT 

### ISSUE THREAD

**Issue by Mikescotland** [skrashevich/double-take#181]
**Is your feature request related to a problem? Please describe.**
Now, the state of person recognised is assigned to a camera for 10 minutes (600 seconds). This is too long, considering automations, like door opening. It means that automation won't work again unless 10 minutes have passed. So for instance, going just to take bins out, or a corner shop, lock won't open, if I return within 10 minutes (camera recognises me going out and sends mqtt)
The MQTT is:
```yaml
{
  "name": "michal",
  "object_id": "double_take_michal",
  "icon": "mdi:account",
  "value_template": "{{ value_json.camera }}",
  "state_topic": "homeassistant/sensor/double-take/michal/state",
  "json_attributes_topic": "homeassistant/sensor/double-take/michal/state",
  "availability_topic": "double-take/available",
  "unique_id": "double_take_michal",
  "expire_after": 600
}
```

**Describe the solution you'd like**
I would like to have option to decrease "expire_after" to just 120 seconds 

**Additional context**
