### ISSUE TITLE
[BUG] 502

### ISSUE THREAD

**Issue by arne182** [skrashevich/double-take#307]
51:07] error: IpDeniedError: Access denied to IP address: ::ffff:192.168.188.129
    at error (/double-take/api/node_modules/express-ipfilter/lib/ipfilter.js:156:17)
    at /double-take/api/node_modules/express-ipfilter/lib/ipfilter.js:202:12
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/double-take/api/node_modules/express/lib/router/index.js:328:13)
    at /double-take/api/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/double-take/api/node_modules/express/lib/router/index.js:346:12)
    at next (/double-take/api/node_modules/express/lib/router/index.js:280:10)
    at module.exports (/double-take/api/src/middlewares/respond.js:54:3)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)

**Comment by skrashevich** [comment]
#297 duplicate ?

**Comment by arne182** [comment]
24-01-31 19:33:43 error: (node:32) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by arne182** [comment]
> #297 duplicate ?

No but might be related. This is the newest beta which you said I should make a new issue

**Comment by skrashevich** [comment]
>  you said I should make a new issue

You wrote that your rc2 is crashing. Describe how this happens, show the configuration and logs.

But before that, try [this build](https://github.com/skrashevich/double-take/pkgs/container/double-take/173027898?tag=sha-ed4203d)

**Comment by arne182** [comment]
Can I seperate this out to another server. Currently I have the home assistant yellow and have installed the add-on via the home assistant UI. The frigate is running on a raspberry Pi 5 and has enough capacity for more computing but how do I get it to communicate with home assistant?

**Comment by skrashevich** [comment]
> Can I seperate this out to another server. Currently I have the home assistant yellow and have installed the add-on via the home assistant UI. The frigate is running on a raspberry Pi 5 and has enough capacity for more computing but how do I get it to communicate with home assistant?

in frigate config:
```yaml
mqtt:
  #enabled: True
  host: 192.168.1.1 # change to your real IP of home assistant yellow 
  user: arne182 # Change the login with which you log into your home-assistant.
  password: punksnotdead # change to password of your HA login
  topic_prefix: frigate # don't touch :)
  ```

and similarly in the double-take configuration:
```yaml
mqtt:
  host: 192.168.1.1 # Similarly to the description above.
  protocol: mqtt # don't touch :)
  username: arne182 # Similarly to the description above.
  password: punksnotdead # Similarly to the description above.
  port: 1883 # don't touch :)
```
