### ISSUE TITLE
[FEAT] Add Bearer tokens to URL requests for API

### ISSUE THREAD

**Issue by greghesp** [skrashevich/double-take#312]
**Is your feature request related to a problem? Please describe.**

When using the[ /recognize](https://double-take.site/#tag/recognize/operation/recognize) API, you pass in a URL.  This URL only works if the endpoint has no authorisation.  For Home Assistant, however, their API requires a bearer token for every request

**Describe the solution you'd like**
Add an auth section to the [camera config](https://github.com/skrashevich/double-take?tab=readme-ov-file#cameras) so that any request to the recognize endpoint uses the bearer token needed

Example:
```
# camera settings (default: shown below)
cameras:
  front-door:
    recognize:
      authorization: "Bearer abc123"
```
