### ISSUE TITLE
[BUG] Pic with bounding box from Frigate snapshot is being used

### ISSUE THREAD

**Issue by TyzzyT** [skrashevich/double-take#354]
**Describe the bug**
When using the snapshots from Frigate, the latest snapshot after the event has finished has a bounding box rendered in the snapshot. This means that the image passed to CompreFace is with a bounding box from Frigate. With Frigate 0.13 you also have a bounding box around the face when using the Frigate+ model, this is causing issues with the detection of faces.
I'd like Frigate to show the bounding boxes on the snapshot image on the Events page, but don't want Double Take to process a snapshot with a bounding box around the face.
Within Frigate I use `clean_copy: True` but I'm not sure if it's possible to only download the snapshot without a bounding box, because the [Frigate docs](https://docs.frigate.video/integrations/api#get-apieventsidsnapshotjpg) say `Accepts the following query string parameters, but they are only applied when an event is in progress. After the event is completed, the saved snapshot is returned from disk without modification`
I'm not sure if this is something Double Take can fix, but I need to start somewhere. If you can't do anything about this problem, I'm more than happy to open an issue in the Frigate repo.

**Version of Double Take**
`v1.13.11.8`

**Expected behavior**
I would expect Double Take to only pass images without a bounding box to CompreFace

**Configuration**
Frigate config
```
    snapshots:
      enabled: true
      clean_copy: true
      bounding_box: true
```

Double Take config
```
frigate:
  url: http://ccab4aaf-frigate-fa-beta:5000 # url of the Frigate server
  update_sub_labels: true # if double take should send matches back to frigate as a sub label
  stop_on_match: false # if set to false all image attempts will be processed before determining the best match
  labels:
    - person
  zones:
    - camera: frontgarden
      zone: frontgarden_zone # only proces images from voortuin zone
  events:
    frontgarden:
      attempts:
        latest: 10 # number of times double take will request a frigate latest.jpg for facial recognition
        snapshot: 10 # number of times double take will request a frigate snapshot.jpg for facial recognition
```
