### ISSUE TITLE
[BUG]Compreface integration not work, No files found, UI rotating indefinitely

### ISSUE THREAD

**Issue by DrissiReda** [skrashevich/double-take#393]
**Describe the bug**
Describe the bug
I'm running a Kubernetes cluster with Double take, frigate, mqtt and compreface.
Frigate capturing objects.
Double take logs show detections but they're not showing up in UI.
In config tab, Compreface is red with error:

```
24-03-14 21:03:13 error: 1 validation error
24-03-14 21:03:13 error: notify is not of a type(s) object
```
It worked a couple of months ago, didn't check until now.

**Additional Logs**

<details><summary>Example of a detection</summary>

```
24-03-14 21:02:26 info: Double Take v1.13.11.8
24-03-14 21:02:26 verbose: {
  telemetry: false,
  auth: true,
  token: { image: '24h' },
  detect: {
    match: {
      save: true,
      base64: false,
      confidence: 60,
      purge: 168,
      min_area: 10000
    },
    unknown: {
      save: true,
      base64: false,
      confidence: 40,
      purge: 8,
      min_area: 0
    }
  },
  time: { timezone: 'Europe/Paris' },
  frigate: {
    attempts: { latest: 10, snapshot: 10, mqtt: true, delay: 0 },
    image: { height: 500 },
    labels: [ 'person' ],
    update_sub_labels: false,
    stop_on_match: true,
    min_area: 0,
    device_tracker_timeout: 30,
    cameras: [],
    url: 'http://frigate.surveillance:5000'
  },
  mqtt: {
    protocol: 'mqtt',
    port: 1883,
    tls: {},
    topics: {
      frigate: 'frigate/events',
      matches: 'double-take/matches',
      cameras: 'double-take/cameras',
      homeassistant: 'homeassistant'
    },
    host: 'rabbitmq.surveillance',
    password: '********',
    username: 'rabbit'
  },
  logs: { level: 'debug', sql: false },
  ui: {
    path: '',
    theme: 'bootstrap4-dark-blue',
    editor: { theme: 'nord_dark' },
    logs: { lines: 5000000 },
    pagination: { limit: 50 },
    thumbnails: { quality: 95, width: 500 }
  },
  server: { port: 3000 },
  cameras: { 'front-door': null, reolink1: { detect: [Object] } },
  detectors: {
    compreface: {
      det_prob_threshold: 0.8,
      timeout: 15,
      opencv_face_required: false,
      key: '********',
      url: 'http://compreface-api.surveillance:8080'
    }
  },
  notify: null,
  schedule: {},
  storage: {
    path: './.storage',
    config: { path: './.storage/config' },
    secrets: { path: './.storage/config', extension: 'yml' },
    media: { path: './.storage' },
    tmp: { path: '/dev/shm/double-take' }
  },
  version: '1.13.11.8'
}
```
</details>

**Versions**
double take: v1.13.11.8
compreface: 1.2.0
frigate: 0.13.2

**Hardware**

    Kubernetes Cluster on top of Rocky OS on amd64
    container image used:  skrashevich/double-take:v1.13.11.8

**Expected behavior**
Compreface to show up green. 
UI to show detections that are showing up in logs.

**Screenshots**
![image](https://github.com/skrashevich/double-take/assets/16291156/74f71164-7090-4e29-9fd1-8c3f230f12ee)

![image](https://github.com/skrashevich/double-take/assets/16291156/ab6b63bd-27af-4f13-a052-c3e19bab8500)

**Comment by ki9us** [comment]
Seeing this without compreface.  I have a feeling compreface is unrelated.  I had while forwarding the docker port over an ssh tunnel and still had it after setting up a reverse proxy (nginx) with TLS.  

![screen](https://github.com/user-attachments/assets/4df16af9-9e8a-4e52-be34-aa31519c1a09)

My config: 

```yaml
mqtt:
  host: ejabberd_container
  user: doubletake@myhost.tld
  password: !secret mqtt_password
  client_id: double-take.myhost.tld
frigate:
  url: http://frigate_container:5000
  update_sub_labels: true
  cameras:
    - backyard
    - driveway
cameras:
  backyard:
    detect:
      match:
        confidence: 50
  driveway:
    detect:
      match:
        confidence: 50
detectors:
  deepstack:
    url: http://deepstack_container:5000
  aiserver:
    url: http://codeprojectai_container:32168
time:
  timezone: America/Denver
```

No browser console errors, just a warning: 

```
In future versions, vue-router support will be removed. Item templating should be used.
```
MQTT is getting messages from frigate on `frigate/backyard/person/snapshot`. 

![snap](https://github.com/user-attachments/assets/49e50e66-504a-4448-ae47-7a2fa62a5ab4)

Double take is also posting to MQTT.  The same user, `doubletake@myhost.tld`, has permission to subscribe to `frigate/#`

![dt-mqtt](https://github.com/user-attachments/assets/318f255f-948b-41a4-a845-01cee3d70897)

No errors in the logs, except when I restart frigate or a detector.
