### ISSUE TITLE
Deepstack 404 Error

### ISSUE THREAD

**Issue by Kosh42** [skrashevich/double-take#468]
I have DeepStack running as here:
![image](https://github.com/skrashevich/double-take/assets/58401509/110a1480-41f0-481b-ac9c-3f020ac652ca)

With the correct face API endpoints available:
![image](https://github.com/skrashevich/double-take/assets/58401509/18a009c7-be50-4cb9-a724-e044d775fe48)

And this in my config:
```
detectors:
  deepstack:
    url: http://192.168.0.45:5001/
    key: ""
    timeout: 15
    opencv_face_required: false
```

But it refuses to connect:
![image](https://github.com/skrashevich/double-take/assets/58401509/0e67373c-7458-4977-8cf1-d2ea448d000d)

Any ideas appreciated as this tool looks awesome!

Thanks in advance.
