### ISSUE TITLE
[BUG] config requires property "detectors"

### ISSUE THREAD

**Issue by townsmcp** [skrashevich/double-take#48]
**Describe the bug**
When loading the config, I get the error message 'config requires property "detectors"'

**Version of Double Take**
v1.13.4

**Expected behavior**
Load DT

**Hardware**
Docker container

**Additional context**
I can jump onto the UI for Frigate, Double Take and CodeProject
Config:
```
# Double Take
# Learn more at https://github.com/skrashevich/double-take/#configuration

mqtt:
  host: 192.168.1.198
  username: mqtt-user
  password: XXXXX

frigate:
  url: http://192.168.1.175:5000
  update_sub_labels: True

# detector settings (default: shown below)
detectors:
  aiserver:
    url: http://192.168.1.175:32168
    # number of seconds before the request times out and is aborted
    timeout: 15
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # only process images from specific cameras, if omitted then all cameras will be processed
    # cameras:
    #   - front-door
    #   - garage
```

![IMG_1448](https://user-images.githubusercontent.com/14061617/235360256-16c639df-8bea-431a-a30d-7d3d7851815c.jpeg)

**Comment by skrashevich** [comment]
I can't reproduce the error. Please give more information about your environment:

- host architecture and OS
- docker run command or docker-compose file contents
- Any other data that may affect this problem

**Comment by townsmcp** [comment]
Strange. 
So my install is Proxmox 7.4-3, Docker is running in an LXC container. LXC is Debian 11.
Docker inside that container is running:

- CompreFace
- Frigate
- Double Take - official version
- Double Take - your version
- CodeProject

I dont have both Double Take versions running at the same time.

I tried installing the official Double Take and that one works with the following config:
```
# Double Take
# Learn more at https://github.com/skrashevich/double-take/#configuration


frigate:
  url: http://192.168.1.175:5000
  update_sub_labels: True

mqtt:
  host: 192.168.1.198
  username: mqtt-user
  password: XXXXXX
  
detectors:
  compreface:
    url: http://192.168.1.175:8000/
    # recognition api key
    key: XXXXXX
    # number of seconds before the request times out and is aborted
    timeout: 15
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    # face_plugins: mask,gender,age
    # only process images from specific cameras, if omitted then all cameras will be processed
    # cameras:
    #   - front-door
    #   - garage
  # aiserver:
  #   url: http://192.168.1.175:32168
  #   # number of seconds before the request times out and is aborted
  #   timeout: 15
  #   # require opencv to find a face before processing with detector
  #   opencv_face_required: false
telemetry: false


    
      
detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 80
    # hours to keep match images until they are deleted
    purge: 48
    # minimum area in pixels to consider a result a match
    min_area: 2500
    #when using substream image, 3600

  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a name as unknown
    confidence: 40
    # hours to keep unknown images until they are deleted
    purge: 8
    # minimum area in pixels to keep an unknown result
    min_area: 0
```
If I run your version of Double Take with the exact same config I get that error.


The compose file for running your version of Double Take is:
```
version: '3.7'

volumes:
  double-take:

services:
  double-take:
    container_name: double-take
    image: skrashevich/double-take
    restart: unless-stopped
    volumes:
      - /opt/double-take:/.storage
    ports:
      - 3000:3000
```

**Comment by skrashevich** [comment]
> The compose file for running your version of Double Take is:

compose file for running original Double Take is exactly same, instead of "image" tag ?

**Comment by townsmcp** [comment]
Yes, same:
```
version: '3.7'

volumes:
  double-take:

services:
  double-take:
    container_name: double-take
    image: jakowenko/double-take
    restart: unless-stopped
    volumes:
      - /opt/double-take:/.storage
    ports:
      - 3000:3000
  ```

**Comment by townsmcp** [comment]
Hmmmm, I have just played around with the containers, stopping official Double Take, pulling up to date CodeProject etc - I can now run your version of Double Take with the following config (effectively same as before but removing aiserver comments):
```
# Double Take
# Learn more at https://github.com/skrashevich/double-take/#configuration


frigate:
  url: http://192.168.1.175:5000
  update_sub_labels: True

mqtt:
  host: 192.168.1.198
  username: mqtt-user
  password: Cheryl198!
  
detectors:
  compreface:
    url: http://192.168.1.175:8000/
    # recognition api key
    key: c11aa2c0-ebf8-4894-8124-93953539ff58
    # number of seconds before the request times out and is aborted
    timeout: 15
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    # face_plugins: mask,gender,age
    # only process images from specific cameras, if omitted then all cameras will be processed
    # cameras:
    #   - front-door
    #   - garage
  aiserver:
    url: http://192.168.1.175:32168
    # number of seconds before the request times out and is aborted
    timeout: 15
    # require opencv to find a face before processing with detector
    opencv_face_required: false
telemetry: false


    
      
detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 80
    # hours to keep match images until they are deleted
    purge: 48
    # minimum area in pixels to consider a result a match
    min_area: 2500
    #when using substream image, 3600

  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a name as unknown
    confidence: 40
    # hours to keep unknown images until they are deleted
    purge: 8
    # minimum area in pixels to keep an unknown result
    min_area: 0
```

This starts up without any error messages, and CodeProject is running fine however I dont seem to be able to get Double Take to talk to CodeProject - the status dots at top of config page isnt showing CodeProject:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/14061617/236410585-143bdb45-d2d8-4a73-bde5-34bb4454c093.png">

To rule out browser cache, I opened all the sessions in new Incognito windows, same issue (missing aiserver/CodeProject as a status
