### ISSUE TITLE
Timeout when connecting to AIserver

### ISSUE THREAD

**Issue by mhoogenbosch** [skrashevich/double-take#49]
I don't really know if this is a bug in Double-Take but I'm hoping it is possible to get some more debugging info.

I run a RaspberryPi 4 with CodeServer.AI as docker image, plain and simple:

```
  double-take:
    container_name: double-take
    image: skrashevich/double-take
#    image: jakowenko/double-take
    restart: unless-stopped
    volumes:
      - /home/pi/.config/appdata/double-take:/.storage
    ports:
      - 3000:3000
```
I'm running the latest version: 1.35.5:

Piece of logging:

```
info: Double Take v1.13.5
info: MQTT: connected
info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot
info: Double Take v1.13.5
info: MQTT: connected
info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot
```

It times out when trying to connect to the AIserver. In the config:

```
  aiserver:
    url: http://192.168.21.9:32168
    # number of seconds before the request times out and is aborted
    timeout: 15
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # only process images from specific cameras, if omitted then all cameras will be processed
    # cameras:
    #   - front-door
    #   - garage
```

In the same config it does connect to comprefase.

Both double take and aiserver are running on the same docker host. It doesn't matter if I use the redirected port or the internal IP of the docker container.

On the docker host I see the port 32168 being open.

Config of the aiserver:

```
  codeproject.ai:
    container_name: codeproject.ai
    image: codeproject/ai-server:rpi64
    restart: unless-stopped
    volumes:
      - ${DOCKERCONFDIR}/codeproject.ai/data:/etc/codeproject/ai
      - ${DOCKERCONFDIR}/codeproject.ai/modules:/app/modules
    ports:
      - 32168:32168
```
Any thoughts of where to start troubleshooting? I tried running the ping command inside the doubletake container, but it the executable isn't there (docker exec -it double-take /bin/bash).

ps. in aiserver I installed the face processing module and the object-detection modules too.

**Comment by skrashevich** [comment]
you need to put double-take and ai.server containers to same network and use internal IP for communicate between them

**Comment by mhoogenbosch** [comment]
yes, same issue. I only have one network, and using the internal 172.18.0.13 IP results in the exact same timeout.

**Comment by skrashevich** [comment]
print output of `docker inspect <container>` command for both ai.server and double-take containers. needs only "NetworkSettings" part

**Comment by mhoogenbosch** [comment]
double-take:

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "2023ea5b237305cc274a168c7ab3ccca1ac2dd29b8bb874b7971651bc66de9fa",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3000"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "3000"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/2023ea5b2373",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "compose_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "double-take",
                        "double-take",
                        "d0ee27f67804"
                    ],
                    "NetworkID": "cd62ebf4a398ab23b85507774a35e300762e712cbc743e818c94a92dd197635b",
                    "EndpointID": "3ee77b58bbe9fc195ee92ecbcad7758e7fd0a6bac2904dd4a1e3b63785258bc4",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.17",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:11",
                    "DriverOpts": null
                }
            }
        }
    }
]
```
aiserver:

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8971a265a380412c9f52ea3c3d3ada044b43a948e4cbde8765a77b1e19503c10",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "32168/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32168"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "32168"
                    }
                ],
                "5000/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/8971a265a380",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "compose_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "codeproject.ai",
                        "codeproject.ai",
                        "6a3b94f1b222"
                    ],
                    "NetworkID": "cd62ebf4a398ab23b85507774a35e300762e712cbc743e818c94a92dd197635b",
                    "EndpointID": "98e4271be389b1f5eda0b8c783fdde5ef0eeb3abc0583bf8d752ac8fe79d00a6",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.13",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:0d",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by skrashevich** [comment]
```
  aiserver:
    url: http://codeproject.ai:32168
    # number of seconds before the request times out and is aborted
    timeout: 15
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # only process images from specific cameras, if omitted then all cameras will be processed
    # cameras:
    #   - front-door
    #   - garage
```

(if it's will not work, put ip 172.18.0.13 instead of "codeproject.ai". I'm not sure how docker works with hostnames with dots)

**Comment by mhoogenbosch** [comment]
> change your config to
> 
> ```
>   aiserver:
>     url: http://codeproject.ai:32168
>     # number of seconds before the request times out and is aborted
>     timeout: 15
>     # require opencv to find a face before processing with detector
>     opencv_face_required: false
>     # only process images from specific cameras, if omitted then all cameras will be processed
>     # cameras:
>     #   - front-door
>     #   - garage
> ```
> 
> (if it's will not work, put ip 172.18.0.13 instead of "codeproject.ai". I'm not sure how docker works with hostnames with dots)

I tried this too, but I get the same timeout with the IP. 

Do you know of any debug logging for double take?

**Comment by skrashevich** [comment]
```
logs:
  level: debug
```

**Comment by skrashevich** [comment]
I have build for you container with some useful tools for troubleshoot, such as ping,traceroute,host,netstat,curl
you can get it on `skrashevich/double-take:latestdebug`. it's the same as latest build, but with additional tools. use it to check connectivity between your docker containers

**Comment by skrashevich** [comment]
fuck. everything was simple. documentation on codeproject site is outdated.

**just use port 5000 instead of 32168**

**Comment by mhoogenbosch** [comment]
> fuck. It's a bug in AI.Server. in some cases, related to docker network type (macvlan of ipvlan) it may stops listen on 32168.
> 
> try to use port 5000 instead of 32168 in config, compose and docker run also, check `CPAI_PORT` environment variable (it must be not set) and `DisableLegacyPort` option in appsettings.json file in ai.server container

And by this you mean 5000:32168 at port settings?

**Comment by skrashevich** [comment]
> And by this you mean 5000:32168 at port settings?

5000:5000, but it doesn't rely to communicate between containers

**Comment by mhoogenbosch** [comment]
mmm.. weird.

It keeps timing out from the GUI of double-take. I now point to url: http://172.18.0.13:32168, but it doesn't matter what I do, if I use 5000 or any other port assignment. It doesn't matter if I point to the 192.168.21.9 IP either, everything times out.

When using your latestdebug build where you have build in curl (tnx for that btw!) it opens the port. When using the command curl -v http://172.18.0.13:32186 it responds immideately. 

See:

```
</html>root@7d8522660379:/double-take# curl -v http://172.18.0.13:32168
* Expire in 0 ms for 6 (transfer 0x55a2a60d80)
*   Trying 172.18.0.13...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55a2a60d80)
* Connected to 172.18.0.13 (172.18.0.13) port 32168 (#0)
> GET / HTTP/1.1
> Host: 172.18.0.13:32168
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 28475
< Content-Type: text/html
< Date: Wed, 03 May 2023 07:54:31 GMT
< Server: Kestrel
< Accept-Ranges: bytes
< ETag: "1d9749638bdefbb"
< Last-Modified: Fri, 21 Apr 2023 21:14:13 GMT

```

**Comment by skrashevich** [comment]
try the latest build.
I still can't reproduce this problem in my environment, but made some changes which potencially can solve

**Comment by mhoogenbosch** [comment]
have you added the chages to latestdebug? 

`23-05-03 09:52:06 error: AxiosError: aiserver process error: timeout of 15000ms exceeded`

**Comment by mhoogenbosch** [comment]
> 

downloading now.

**Comment by skrashevich** [comment]
> downloading now.

is problem solved?

**Comment by mhoogenbosch** [comment]
> > downloading now.
> 
> is problem solved?

My apologies. I had a draft reply but haven't hit the comment button, but unfortunately it doesn't help. It keeps timing out. 

The weird thing is it can connect from within the container over the port (curl -v command), why it times out doesn't make sense to me at all.

**Comment by skrashevich** [comment]
@mhoogenbosch is face processing module enabled and running?

main page of ai.server must looks like as this:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/15078499/236410148-599a543e-a904-4dfa-8683-7dbbc1a14618.png">
"Face processing" row must exists and have green background

**Comment by skrashevich** [comment]
@mhoogenbosch you need to go to "Install Modules" tab, Uninstall and then Install again "Face Processing" module.
After that, it should work. Please note that the installation may take a long time (about half an hour)

**Comment by mhoogenbosch** [comment]
> @mhoogenbosch you need to go to "Install Modules" tab, Uninstall and then Install again "Face Processing" module. After that, it should work. Please note that the installation may take a long time (about half an hour)

![image](https://user-images.githubusercontent.com/36899598/236424553-17fa401c-ead3-4996-9c38-4e93b15a1780.png)

**Comment by skrashevich** [comment]
> After reinstalling i'm getting the exact same issue.

try to clean reinstall... don't forget to remove contents of volumes:
      - ${DOCKERCONFDIR}/codeproject.ai/data:/etc/codeproject/ai
      - ${DOCKERCONFDIR}/codeproject.ai/modules:/app/modules

**Comment by skrashevich** [comment]
> Annoying there is no 2.1.8 for ARM64, latest version is 2.1.4.

do you testing oncodeproject/ai-server:**arm64-2.1.4** or oncodeproject/ai-server:**rpi64-2.1.4** ?

**Comment by mhoogenbosch** [comment]
> > Annoying there is no 2.1.8 for ARM64, latest version is 2.1.4.
> 
> do you testing oncodeproject/ai-server:**arm64-2.1.4** or oncodeproject/ai-server:**rpi64-2.1.4** ?

arm64, but doesn't matter if I enter rpi64 or arm64, it doesn't pull a new image which means they are the same.

**Comment by mhoogenbosch** [comment]
Right.. so 

the tag rpi64 leads to 2.1.4 and arm64 to 2.1.3. So I'm back using rpi64. 

the face detection module is started and online when double take is not connected. 

![image](https://github.com/skrashevich/double-take/assets/36899598/1a648360-5c84-428c-bea3-d6dc27d7d287)

as soon as i change the config to talk to the aiserver, it crashes. If I piont it to another aiserver instance running on an old HP TC620, based on AMD64 image it runs.

I don't think there is anything in my config which could explain this?

```
# Double Take
# Learn more at https://github.com/jakowenko/double-take/#configuration
mqtt:
  host: 192.168.30.35
  username: mosquitto
  password: mosquitto

frigate:
  url: http://192.168.21.92:5000
  attempts:
    # number of times double take will request a frigate latest.jpg for facial recognition
    latest: 10
    # number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 10
    # process frigate images from frigate/+/person/snapshot topics
    mqtt: true
    # add a delay expressed in seconds between each detection loop
    delay: 0

  image:
    # height of frigate image passed for facial recognition
    height: 500

detectors:
#  deepstack:
#    url: http://192.168.21.92:5001
#    key:
#    opencv_face_required: false
      # only process images from specific cameras, if omitted then all cameras will be processed
      # cameras:
      #   - front-door
      #   - garage
      
  compreface:
    url: http://192.168.21.92:8000
    # recognition api key
    key: 971ec64d-b0c2-4f59-9e16-cb9a6e4b0f88
    # number of seconds before the request times out and is aborted
    timeout: 15
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: false

  aiserver:
    #url: http://172.18.0.13:32168 // internal docker url
    #url: http://192.168.22.107:5000 // hp tc620
    url: http://192.168.21.9:5000 
    # number of seconds before the request times out and is aborted
    timeout: 15
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # only process images from specific cameras, if omitted then all cameras will be processed
    # cameras:
    #   - front-door
    #   - garage
```
