### ISSUE TITLE
[BUG]  error: compreface process error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by aik** [skrashevich/double-take#621]
**Describe the bug**
No face recognition working. Compreface shows no activity. Frigate logs show successful downloads of snapshots though.
192.168.10.214 runs double-take, compreface, frigate, all in docker.
192.168.10.104 runs mosquitto and HA (but I am not even trying HA yet).
Double-take keeps failing connecting to some service on port 80 - what is it? netstat shows nothing on this port.

**Version of Double Take**
`v1.13.11.8`

**Expected behavior**
Some activity should happen in Compreface.

**Screenshots**
```
double-take    | error: compreface process error: connect ECONNREFUSED 127.0.0.1:80                                              
double-take    | Error: connect ECONNREFUSED 127.0.0.1:80                                                                        
double-take    |     at AxiosError.from (/double-take/api/node_modules/axios/dist/node/axios.cjs:836:14)                         
double-take    |     at RedirectableRequest.handleRequestError (/double-take/api/node_modules/axios/dist/node/axios.cjs:3086:25) 
double-take    |     at RedirectableRequest.emit (node:events:529:35)                                                            
double-take    |     at eventHandlers.<computed> (/double-take/api/node_modules/follow-redirects/index.js:38:24)                 
double-take    |     at ClientRequest.emit (node:events:517:28)                                                                  
double-take    |     at Socket.socketErrorListener (node:_http_client:501:9)                                                     
double-take    |     at Socket.emit (node:events:517:28)                                                                         
double-take    |     at emitErrorNT (node:internal/streams/destroy:151:8)                                                        
double-take    |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)                                                   
double-take    |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)                              
double-take    |     at Axios.request (/double-take/api/node_modules/axios/dist/node/axios.cjs:3876:41)                          
double-take    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                               
double-take    |     at async module.exports.process (/double-take/api/src/util/process.util.js:178:22)                          
double-take    |     at async Promise.all (index 0)                                                                              
double-take    |     at async module.exports.start (/double-take/api/src/util/process.util.js:160:17)                            
double-take    |     at async module.exports.polling (/double-take/api/src/util/process.util.js:55:25)                           
double-take    |     at async Promise.all (index 0)                                                                              
double-take    |     at async module.exports.start (/double-take/api/src/controllers/recognize.controller.js:152:7)              
double-take    | info: done processing roof: 1748352584.436948-z9z15z in 20.81 sec                                               

```
**Hardware**
- amd64
- ubuntu 2404
- Docker image (if applicable): skrashevich/double-take

**Configuration**
```
aik@srv ~> cat double-take/config/config.yml
mqtt:
  host: 192.168.10.104

frigate:
  url: http://192.168.10.214:5000

detectors:
  compreface:
    url: 192.168.10.214
    key: 640075b-fa05-463e-111111111111111
    timeout: 15
    det_prob_threshold: 0.8
    opencv_face_required: false

aik@srv ~> cat double-take/docker-compose-aik.yaml
version: '3.7'

volumes:
  double-take:

services:
  double-take:
    container_name: double-take
    image: skrashevich/double-take
    restart: unless-stopped
    volumes:
      - /home/aik/double-take:/.storage
    ports:
      - 3000:3000
```
