### ISSUE TITLE
[BUG] No person events published to double-take or homeassistant topics

### ISSUE THREAD

**Issue by instantdreams** [skrashevich/double-take#622]
**Describe the bug**
No events published to either the double-take or homeassistant topics

**Version of Double Take**
`1.13.11.8`

**Expected behavior**
I have configured frigate, mqtt, double-take, and ai-server. They communicate with each other and detection is working. However, events are not published to either `double-take/matches/` or `homeassistant/sensor/double-take/person/`.

**Hardware**
 - Architecture or platform: amd64 Intel NUC
 - OS: Debian 6.1.135-1 (2025-04-25) x86_64 GNU/Linux
 - Browser: Firefox
 - Docker image: skrashevich/double-take:latest

**Configuration**
Relevant sections from frigate config.yaml:

```
mqtt:
  enabled: true
  host: 192.168.1.93
  port: 1883
  topic_prefix: frigate
  client_id: frigate

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: false
  crop: true
  height: 500
  quality: 100
  retain:
    default: 32
```

Relevant section from mosquitto.conf:

```
# General
allow_anonymous true
log_dest file /mosquitto/log/mosquitto.log
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
log_type error
log_type warning
persistence true
persistence_location /mosquitto/data/
# Listeners
listener 1883
protocol mqtt
```

All of double-take config.yml:

```
auth: false
mqtt:
  protocol: mqtt
  host: 192.168.1.93
  port: 1883
  client_id: double-take
  topics:
    frigate: frigate/events
    matches: double-take/matches
    cameras: double-take/cameras
    homeassistant: homeassistant
detect:
  match:
    save: true
    base64: false
    confidence: 80
    purge: 240
    min_area: 10000
  unknown:
    save: true
    base64: false
    confidence: 40
    purge: 8
    min_area: 0
frigate:
  url: http://192.168.1.94:5000
  update_sub_labels: true
  stop_on_match: true
  min_area: 0
  labels:
    - person
  attempts:
    latest: 10
    snapshot: 10
    mqtt: true
    delay: 0
  image:
    height: 500
  cameras:
    - front
  zones:
    - camera: front
      zone: front_steps
  events:
    front:
      attempts:
        latest: 5
        snapshot: 5
        mqtt: false
        delay: 1
    device_tracker_timeout: 30
  device_tracker_timeout: 30
detectors:
  aiserver:
    url: http://192.168.1.94:32168
    timeout: 15
    opencv_face_required: false
    cameras:
      - front
time:
  timezone: UTC
logs:
  level: info
  sql: false
ui:
  path: ''
  pagination:
    limit: 50
  thumbnails:
    quality: 95
    width: 500
  logs:
    lines: 500
  theme: bootstrap4-dark-blue
  editor:
    theme: nord_dark
telemetry: false
server:
  port: 3000
storage:
  path: ./.storage
  config:
    path: ./.storage/config
  secrets:
    path: ./.storage/config
    extension: yml
  media:
    path: ./.storage
  tmp:
    path: /dev/shm/double-take
```

**Additional context**
Log for double-take:

```
25-06-13 09:57:47 info: Double Take v1.13.11.8
25-06-13 09:57:48 info: MQTT: connected
25-06-13 09:57:48 info: MQTT: subscribed to frigate/events, frigate/front/person/snapshot
```

Triggering a detection and monitoring the mqtt payloads via MQTTX reveals that nothing ever appears in the matches or person events.

![Image](https://github.com/user-attachments/assets/1e8cb13b-9e26-41b8-a03d-5224e1d30793)

**Comment by instantdreams** [comment]
I am getting payloads on topics `homeassistant/sensor/double-take/front/state` and `homeassistant/sensor/double-take/unknown/state` but I think they are not reporting correctly.

In my double-take config.yml file I have the following:

```
detect:
  match:
    save: true
    base64: false
    confidence: 80
    purge: 240
    min_area: 10000
  unknown:
    save: true
    base64: false
    confidence: 40
    purge: 8
    min_area: 0
```

To me this indicates that a confidence of 80 or higher would report a match, but this payload indicates the result was a miss:

```
{
  "id": "1750346363.151137-vgppjq",
  "duration": 6.78,
  "timestamp": "2025-06-19T15:19:48.306Z",
  "attempts": 6,
  "camera": "front",
  "zones": [
    "front_steps"
  ],
  "matches": [],
  "misses": [
    {
      "name": "dean",
      "confidence": 81.06,
      "match": false,
      "box": {
        "top": 74,
        "left": 271,
        "width": 83,
        "height": 110
      },
      "checks": [
        "box area too low: 9130 < 10000"
      ],
      "type": "latest",
      "duration": 0.37,
      "detector": "aiserver",
      "filename": "5707f6f9-2260-4906-9981-796c7fe25771.jpg",
      "base64": null
    }
  ],
  "unknowns": [],
  "personCount": 1,
  "counts": {
    "person": 1,
    "match": 0,
    "miss": 1,
    "unknown": 0
  }
}
```

Does the box size issue override the confidence?
