### ISSUE TITLE
[FEAT] Add Zones Option to Detectors 

### ISSUE THREAD

**Issue by asherry99** [skrashevich/double-take#89]
**Is your feature request related to a problem? Please describe.**
I would like to use zones within a detector. Similar to how notify has the option.
```
    # only notify from specific zones
    # zones:
    #   - camera: garage
    #     zone: driveway
```

**Describe the solution you'd like**
I've been playing with Rekognition and it's been the best option for me for high quality matches.  But the costs can get high, Ideally I would love to use zones to limit Rekognition to my frigate porch zone, but still use a cheaper option like AIServer for my other zones; front yard, driveway, etc..

**Notes:**
- This is a Nice-To-Have and by no means critical to the usage.
- I had [created this on the original double-take repo](https://github.com/jakowenko/double-take/issues/284), but since I am now using this fork I figured I'd create it here as well.

**Comment by skrashevich** [comment]
https://github.com/skrashevich/double-take#frigate-1
```
frigate:
# only process images from specific zones
  zones:
    # - camera: garage
    #   zone: driveway
```

This feature has already been implemented

**Comment by asherry99** [comment]
Wow, I can't believe I missed that. Thank you!

**Comment by asherry99** [comment]
So after exploring this more, I'd like to reopen the issue. You are correct I can totally scope the incoming frigate requests to double-take to certain zones. But what I'm after is allowing all zones to be sent, but them limiting the detectors to zones instead of by cameras.

Example: So `zone_1` would go to aiserver while `zone_2` would go to Rekognition. 

I tried with the following config on v.1.13.11 and wasn't able to get per zone as an option to work. Did I screw up the usage, or is this not supported?

```
detectors:
  rekognition:
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    aws_region: "us-west-2"
    collection_id: double-take
    zones:
      - zone_1
      - zone_2

  aiserver:
    url: http://10.40.3.250:32168
    timeout: 15
#    cameras:
#      - camera_1
#      - camera_2
      zones:
        - zone_3
        - zone_4
  ```
